apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: bench-role
                      operator: In
                      values:
                        - kafka
    version: 2.3.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
        - type: persistent-claim
          class: manual
          size: 10Gi
          deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: manual
      size: 10Gi
      deleteClaim: true
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: bench-role
                      operator: In
                      values:
                        - kafka
  entityOperator:
    topicOperator: {}
    userOperator: {}